### ISSUE TITLE
这个不支持国密算法吧?

### ISSUE THREAD

**Issue by YcSnail** [chenpkg/cmb#1]
招行聚合支付2.8文档中.介绍

生成签名值
数字签名采用SM2withSM3签名算法，签名方式为PKCS#1裸签名，签名USER_ID使用国密局推荐ID，即“12345678123456789”，使用国密私钥对签名字符串进行加签，生成签名值。

代码中没有看到这部分处理

**Comment by chenpkg** [comment]
是的，这个是针对2.7版本的聚合支付。
2.7版本之后签名方式的招行新商户强制使用sm2国密签名方式，老版本商户还是可以使用 RSA 签名方式

**Comment by YcSnail** [comment]
好的.目前公司业务需求.需要使用基于国密的版本.  大佬以后可以搞个支持2.8的版本.我这边功能目前还在测试中

找到一个库.大佬以后做的话.可以参考下:
https://gitee.com/laoqianjunzi/polypay

多谢
